export default [
  {
    name: "manchego",
    region: "Castille",
    country: "Spain",
    milk: "cow",
    certification: "AOP",
    certification_date: "1996",
    beginning: 9,
    end: 1,
  },
  {
    name: "abondance",
    region: "Haute-Savoie",
    country: "France",
    milk: "cow",
    certification: "AOP",
    certification_date: "1990",
    beginning: 6,
    end: 12,
  },
  {
    name: "banon",
    region: "Alpes-de-Haute-Provence",
    country: "France",
    milk: "goat",
    certification: "AOP",
    certification_date: "2003",
    beginning: 1,
    end: 12,
  },
  {
    name: "beaufort",
    region: "Savoie",
    country: "France",
    milk: "cow",
    certification: "AOP",
    certification_date: "1968",
    beginning: 4,
    end: 9,
  },
  {
    name: "bleu d’Auvergne",
    region: "Auvergne",
    country: "France",
    milk: "cow",
    certification: "AOP",
    certification_date: "1975",
    beginning: 6,
    end: 12,
  },
  {
    name: "bleu de Gex",
    region: "Haut-Jura",
    country: "France",
    milk: "cow",
    certification: "AOP",
    certification_date: "1977",
    beginning: 6,
    end: 2,
  },
  {
    name: "bleu des Causses",
    region: "sud du Massif central",
    country: "France",
    milk: "cow",
    certification: "AOP",
    certification_date: "1991",
    beginning: 6,
    end: 1,
  },
  {
    name: "bleu du Vercors-Sassenage",
    region: "Drôme, Isère",
    country: "France",
    milk: "cow",
    certification: "AOP",
    certification_date: "1998",
    beginning: 6,
    end: 11,
  },
  {
    name: "boulette d'Avennes",
    region: "pays Avesnois",
    country: "France",
    milk: "cow",
    certification: "",
    certification_date: "",
    beginning: 5,
    end: 10,
  },
  {
    name: "brie de Meaux",
    region: "Seine-et-Marne, Loiret, Meuse, Aube, Marne, Haute-Marne, Yonne",
    country: "France",
    milk: "cow",
    certification: "AOP",
    certification_date: "1996",
    beginning: 7,
    end: 3,
  },
  {
    name: "brie de Melun",
    region: "Seine-et-Marne, Yonne, Aube",
    country: "France",
    milk: "cow",
    certification: "AOP",
    certification_date: "2009",
    beginning: 7,
    end: 3,
  },
  {
    name: "brillat-savarin",
    region: "Seine-Maritime",
    country: "France",
    milk: "cow",
    certification: "IGP",
    certification_date: "2017",
    beginning: 4,
    end: 10,
  },
  {
    name: "brocciu",
    region: "Corse",
    country: "France",
    milk: "sheep|goat",
    certification: "AOP",
    certification_date: "1998",
    beginning: 3,
    end: 12,
  },
  {
    name: "cabécou",
    region: "Massif central",
    country: "France",
    milk: "goat",
    certification: "",
    certification_date: "",
    beginning: 4,
    end: 8,
  },
  {
    name: "camembert de Normandie",
    region: "Normandie",
    country: "France",
    milk: "cow",
    certification: "AOC",
    certification_date: "1983",
    beginning: 5,
    end: 10,
  },
  {
    name: "cancoillotte",
    region: "Franche-Comté",
    country: "France",
    milk: "cow",
    certification: "",
    certification_date: "",
    beginning: 1,
    end: 12,
  },
  {
    name: "cantal",
    region: "Massif central",
    country: "France",
    milk: "cow",
    certification: "AOC",
    certification_date: "1956",
    beginning: 5,
    end: 1,
  },
  {
    name: "chabichou du Poitou",
    region: "Poitou",
    country: "France",
    milk: "goat",
    certification: "AOC",
    certification_date: "1990",
    beginning: 6,
    end: 11,
  },
  {
    name: "chaource",
    region: "Aube",
    country: "France",
    milk: "cow",
    certification: "AOC",
    certification_date: "1970",
    beginning: 7,
    end: 11,
  },
  {
    name: "charolais",
    region: "Bourgogne",
    country: "France",
    milk: "goat",
    certification: "AOP",
    certification_date: "2010",
    beginning: 4,
    end: 11,
  },
  {
    name: "chavignol",
    region: "Berry",
    country: "France",
    milk: "goat",
    certification: "AOC",
    certification_date: "1976",
    beginning: 4,
    end: 11,
  },
  {
    name: "chevrotin",
    region: "Savoie, Haute-Savoie",
    country: "France",
    milk: "goat",
    certification: "AOC",
    certification_date: "2002",
    beginning: 4,
    end: 9,
  },
  {
    name: "comté",
    region: "Franche-Comté",
    country: "France",
    milk: "cow",
    certification: "AOC",
    certification_date: "1958",
    beginning: 8,
    end: 3,
  },
  {
    name: "coulommiers",
    region: "Seine-et-Marne",
    country: "France",
    milk: "cow",
    certification: "",
    certification_date: "",
    beginning: 3,
    end: 7,
  },
  {
    name: "emmental de Savoie",
    region: "Savoie, Haute-Savoie, Ain",
    country: "France",
    milk: "cow",
    certification: "IGP",
    certification_date: "1996",
    beginning: 5,
    end: 10,
  },
  {
    name: "époisses",
    region: "Côte-d'Or, Yonne, Haute-Marne",
    country: "France",
    milk: "cow",
    certification: "AOC",
    certification_date: "1991",
    beginning: 5,
    end: 10,
  },
  {
    name: "fourme d’Ambert",
    region: "Massif central",
    country: "France",
    milk: "cow",
    certification: "AOC",
    certification_date: "1972",
    beginning: 5,
    end: 10,
  },
  {
    name: "fourme de Montbrison",
    region: "Loire, Puy-de-Dôme",
    country: "France",
    milk: "cow",
    certification: "AOC",
    certification_date: "1972",
    beginning: 10,
    end: 4,
  },
  {
    name: "laguiole",
    region: "Aubrac",
    country: "France",
    milk: "cow",
    certification: "AOC",
    certification_date: "1961",
    beginning: 9,
    end: 3,
  },
  {
    name: "langres",
    region: "Haute-Marne",
    country: "France",
    milk: "cow",
    certification: "AOC",
    certification_date: "1991",
    beginning: 5,
    end: 12,
  },
  {
    name: "livarot",
    region: "Calvados, Eure, Orne",
    country: "France",
    milk: "cow",
    certification: "AOC",
    certification_date: "1975",
    beginning: 5,
    end: 9,
  },
  {
    name: "mâconnais",
    region: "Rhône, Saône-et-Loire",
    country: "France",
    milk: "goat",
    certification: "AOP",
    certification_date: "2006",
    beginning: 5,
    end: 9,
  },
  {
    name: "maroilles",
    region: "Aisne, Nord",
    country: "France",
    milk: "cow",
    certification: "AOC",
    certification_date: "1955",
    beginning: 7,
    end: 3,
  },
  {
    name: "mimolette",
    region: "Nord",
    country: "France",
    milk: "cow",
    certification: "",
    certification_date: "",
    beginning: 4,
    end: 9,
  },
  {
    name: "morbier",
    region: "massif du Jura",
    country: "France",
    milk: "cow",
    certification: "AOC",
    certification_date: "2000",
    beginning: 1,
    end: 3,
  },
  {
    name: "munster",
    region: "Est de la France",
    country: "France",
    milk: "cow",
    certification: "AOC",
    certification_date: "1969",
    beginning: 5,
    end: 10,
  },
  {
    name: "murol du Grand Bérioux",
    region: "Auvergne",
    country: "France",
    milk: "cow",
    certification: "",
    certification_date: "",
    beginning: 4,
    end: 7,
  },
  {
    name: "neufchâtel",
    region: "Seine-Maritime, Oise",
    country: "France",
    milk: "cow",
    certification: "AOC",
    certification_date: "1969",
    beginning: 5,
    end: 8,
  },
  {
    name: "ossau-iraty",
    region: "Pyrénées-Atlantiques, Hautes-Pyrénées",
    country: "France",
    milk: "sheep",
    certification: "AOC",
    certification_date: "1980",
    beginning: 6,
    end: 11,
  },
  {
    name: "pélardon",
    region: "Languedoc",
    country: "France",
    milk: "goat",
    certification: "AOP",
    certification_date: "2001",
    beginning: 5,
    end: 9,
  },
  {
    name: "picodon",
    region: "Cévennes, Préalpes drômoises",
    country: "France",
    milk: "goat",
    certification: "AOC",
    certification_date: "1983",
    beginning: 5,
    end: 1,
  },
  {
    name: "pont-l’évêque",
    region: "Normandie",
    country: "France",
    milk: "cow",
    certification: "AOC",
    certification_date: "1972",
    beginning: 6,
    end: 3,
  },
  {
    name: "pouligny-saint-pierre",
    region: "Indre",
    country: "France",
    milk: "goat",
    certification: "AOC",
    certification_date: "1972",
    beginning: 6,
    end: 10,
  },
  {
    name: "reblochon",
    region: "Savoie, Haute-Savoie",
    country: "France",
    milk: "cow",
    certification: "AOC",
    certification_date: "1958",
    beginning: 5,
    end: 9,
  },
  {
    name: "rigotte de Condrieu",
    region: "Pilat",
    country: "France",
    milk: "goat",
    certification: "AOP",
    certification_date: "2009",
    beginning: 5,
    end: 8,
  },
  {
    name: "rocamadour",
    region: "Lot, Lot-et-Garonne",
    country: "France",
    milk: "goat",
    certification: "AOC",
    certification_date: "1995",
    beginning: 4,
    end: 9,
  },
  {
    name: "roquefort",
    region: "Aveyron",
    country: "France",
    milk: "sheep",
    certification: "AOC",
    certification_date: "1925",
    beginning: 1,
    end: 8,
  },
  {
    name: "saint-félicien",
    region: "Dauphiné",
    country: "France",
    milk: "cow",
    certification: "",
    certification_date: "",
    beginning: 4,
    end: 9,
  },
  {
    name: "saint-marcellin",
    region: "Isère",
    country: "France",
    milk: "cow",
    certification: "IGP",
    certification_date: "2013",
    beginning: 7,
    end: 7,
  },
  {
    name: "saint-nectaire",
    region: "Auvergne",
    country: "France",
    milk: "cow",
    certification: "AOC",
    certification_date: "1964",
    beginning: 9,
    end: 11,
  },
  {
    name: "sainte-maure-de-touraine",
    region: "Touraine",
    country: "France",
    milk: "goat",
    certification: "AOC",
    certification_date: "1990",
    beginning: 4,
    end: 8,
  },
  {
    name: "salers",
    region: "Massif central",
    country: "France",
    milk: "cow",
    certification: "AOC",
    certification_date: "1961",
    beginning: 1,
    end: 12,
  },
  {
    name: "selles-sur-cher",
    region: "Loir-et-Cher, Cher, Indre",
    country: "France",
    milk: "goat",
    certification: "AOC",
    certification_date: "1986",
    beginning: 4,
    end: 8,
  },
  {
    name: "tome des Bauges",
    region: "Savoie, Haute-Savoie",
    country: "France",
    milk: "cow",
    certification: "AOC",
    certification_date: "2002",
    beginning: 5,
    end: 8,
  },
  {
    name: "tomme de sheep des Pyrénées",
    region: "Pyrénées-Atlantiques, Hautes-Pyrénées",
    country: "France",
    milk: "sheep",
    certification: "",
    certification_date: "",
    beginning: 5,
    end: 10,
  },
  {
    name: "tomme de Savoie",
    region: "Savoie, Haute-Savoie",
    country: "France",
    milk: "cow",
    certification: "IGP",
    certification_date: "1996",
    beginning: 8,
    end: 2,
  },
  {
    name: "valençay",
    region: "Indre",
    country: "France",
    milk: "goat",
    certification: "AOP",
    certification_date: "1998",
    beginning: 6,
    end: 9,
  },
  {
    name: "mont-d’or",
    region: "Doubs, Canton de Vaud",
    country: "France|Switzerland",
    milk: "cow",
    certification: "AOC",
    certification_date: "1983",
    beginning: 11,
    end: 2,
  },
  {
    name: "feta",
    region: "Épire",
    country: "Greece",
    milk: "goat|sheep",
    certification: "AOP",
    certification_date: "2012",
    beginning: 4,
    end: 11,
  },
  {
    name: "burrata",
    region: "Pouilles",
    country: "Italy",
    milk: "cow|bufflonne",
    certification: "",
    certification_date: "",
    beginning: 5,
    end: 8,
  },
  {
    name: "fontina",
    region: "Vallée d'Aoste",
    country: "Italy",
    milk: "cow",
    certification: "AOP",
    certification_date: "2002",
    beginning: 4,
    end: 9,
  },
  {
    name: "gorgonzola",
    region: "Lombardie",
    country: "Italy",
    milk: "cow",
    certification: "AOP",
    certification_date: "1996",
    beginning: 4,
    end: 11,
  },
  {
    name: "grana padano",
    region: "Italy septentrionale",
    country: "Italy",
    milk: "cow",
    certification: "AOP",
    certification_date: "1996",
    beginning: 5,
    end: 8,
  },
  {
    name: "mascarpone",
    region: "Piémont, Lombardie",
    country: "Italy",
    milk: "cow",
    certification: "",
    certification_date: "",
    beginning: 1,
    end: 12,
  },
  {
    name: "mozzarella di bufala",
    region: "Campanie",
    country: "Italy",
    milk: "cow|bufflonne",
    certification: "AOP",
    certification_date: "1996",
    beginning: 1,
    end: 12,
  },
  {
    name: "parmigiano-reggiano",
    region: "Émilie-Romagne",
    country: "Italy",
    milk: "cow",
    certification: "AOP",
    certification_date: "1996",
    beginning: 1,
    end: 12,
  },
  {
    name: "pecorino romano",
    region: "Latium",
    country: "Italy",
    milk: "sheep",
    certification: "AOP",
    certification_date: "1996",
    beginning: 5,
    end: 9,
  },
  {
    name: "provolone",
    region: "Piémont, Lombardie, Vénétie",
    country: "Italy",
    milk: "cow",
    certification: "AOP",
    certification_date: "1996",
    beginning: 6,
    end: 10,
  },
  {
    name: "ricotta",
    region: "Piémont, Lombardie",
    country: "Italy",
    milk: "cow|sheep|goat|bufflonne",
    certification: "",
    certification_date: "",
    beginning: 6,
    end: 9,
  },
  {
    name: "scamorza",
    region: "Campanie",
    country: "Italy",
    milk: "cow|sheep",
    certification: "STG",
    certification_date: "1998",
    beginning: 1,
    end: 12,
  },
  {
    name: "taleggio",
    region: "Lombardie",
    country: "Italy",
    milk: "cow",
    certification: "AOP",
    certification_date: "1996",
    beginning: 7,
    end: 10,
  },
  {
    name: "edam",
    region: "Hollande-Septentrionale",
    country: "Netherlands",
    milk: "cow",
    certification: "",
    certification_date: "",
    beginning: 1,
    end: 12,
  },
  {
    name: "gouda",
    region: "Hollande-Méridionale",
    country: "Netherlands",
    milk: "cow",
    certification: "AOP",
    certification_date: "1992",
    beginning: 5,
    end: 10,
  },
  {
    name: "cheddar",
    region: "Somerset",
    country: "United Kingdom",
    milk: "cow",
    certification: "AOP",
    certification_date: "1996",
    beginning: 1,
    end: 12,
  },
  {
    name: "stilton",
    region: "Derbyshire, Leicestershire, Nottinghamshire",
    country: "United Kingdom",
    milk: "cow",
    certification: "AOP",
    certification_date: "1996",
    beginning: 10,
    end: 3,
  },
  {
    name: "emmental",
    region: "Canton de Berne",
    country: "Switzerland",
    milk: "cow",
    certification: "AOP",
    certification_date: "2006",
    beginning: 1,
    end: 12,
  },
  {
    name: "etivaz",
    region: "Préalpes, Alpes vaudoises",
    country: "Switzerland",
    milk: "cow",
    certification: "AOC",
    certification_date: "2000",
    beginning: 3,
    end: 10,
  },
  {
    name: "gruyère",
    region: "Fribourg, Vaud, Neuchâtel, Jura",
    country: "Switzerland",
    milk: "cow",
    certification: "AOP",
    certification_date: "2001",
    beginning: 10,
    end: 2,
  },
  {
    name: "raclette",
    region: "Savoie, Valais",
    country: "France|Switzerland",
    milk: "cow",
    certification: "AOP",
    certification_date: "2003",
    beginning: 11,
    end: 4,
  },
  {
    name: "tête de moine",
    region: "Jura bernois",
    country: "Switzerland",
    milk: "cow",
    certification: "AOP",
    certification_date: "2011",
    beginning: 9,
    end: 12,
  },
].sort((a, b) => (a.name > b.name ? 1 : -1));
